version: '3'
services:
  caddy:
    image: caddy:2.3.0
    restart: always
    depends_on:
      - minio
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile_single:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  
  minio:
    image: minio/minio:RELEASE.2021-01-30T00-20-58Z
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio  
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio_data_single:/data
    command: server /data

volumes:
  caddy_data:
  caddy_config:
  minio_data_single:

